command:
  - "python"
  - "-m"
  - "uvicorn"
  - "app:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8000"

env:
  - name: ENDPOINT_NAME
    value: "<your-endpoint>"
  - name: LAKEBASE_PROJECT
    value: "<your-lakebase-project-name>"
  - name: DB_SCHEMA
    value: "ecommerce"

resources:
  - name: postgres
    type: postgres
    postgres:
      branch_id: "projects/<your-lakebase-project-name>/branches/production"
      database: "databricks_postgres"